web:
  build: .
  volumes:
   - .:/code
  links:
   - redis
  expose:
   - "32000"
redis:
  image: redis
lb:
  image: tutum/haproxy
  links:
   - web
  ports:
   - "20000:80"
  environment:
   - BACKEND_PORT=5000
   - BALANCE=roundrobin
